
-- EXERCICIO A
SELECT 
	A.NMPRODUCT,
	COUNT(B.CDPRODUCT) AS TOTALSELLS
FROM PRODUCT A
INNER JOIN PRODUCTREQUEST B ON A.CDPRODUCT = B.CDPRODUCT
WHERE A.CDPRODUCT IN (
	SELECT CDPRODUCT FROM PRODUCTREQUEST
)
GROUP BY A.NMPRODUCT

UNION ALL 

SELECT 
	NMPRODUCT,
	NULL
FROM PRODUCT 
WHERE CDPRODUCT NOT IN (
	SELECT CDPRODUCT FROM PRODUCTREQUEST
)
GROUP BY NMPRODUCT;

-- EXERCICIO B
SELECT 
	A.NMSUPPLIER,
	COUNT(B.CDPRODUCT) AS QTPRODUCTS
FROM SUPPLIER A
INNER JOIN PRODUCT B ON A.CDSUPPLIER = B.CDSUPPLIER
WHERE A.CDSUPPLIER IN (
	SELECT CDSUPPLIER FROM PRODUCT
)
GROUP BY A.NMSUPPLIER

UNION ALL

SELECT 
	NMSUPPLIER,
	NULL
FROM SUPPLIER
WHERE CDSUPPLIER NOT IN (
	SELECT CDSUPPLIER FROM PRODUCT
)
GROUP BY NMSUPPLIER;

-- EXERCICIO C
SELECT 
	A.NMSUPPLIER,
	B.NMPRODUCT,
	SUM(C.QTAMOUNT) AS TOTALSELL
FROM SUPPLIER A 
INNER JOIN PRODUCT B ON A.CDSUPPLIER = B.CDSUPPLIER
INNER JOIN PRODUCTREQUEST C ON B.CDPRODUCT = C.CDPRODUCT
GROUP BY A.NMSUPPLIER, B.NMPRODUCT

UNION ALL

SELECT 
	A.NMSUPPLIER, 'TOTALSUPPLIER',
	SUM(C.QTAMOUNT) AS TOTAL
FROM SUPPLIER A 
INNER JOIN PRODUCT B ON A.CDSUPPLIER = B.CDSUPPLIER
INNER JOIN PRODUCTREQUEST C ON B.CDPRODUCT = C.CDPRODUCT
GROUP BY A.NMSUPPLIER

UNION ALL

SELECT 
	'GENERALTOTAL','',
	SUM(C.QTAMOUNT) AS TOTALSELL
FROM SUPPLIER A 
INNER JOIN PRODUCT B ON A.CDSUPPLIER = B.CDSUPPLIER
INNER JOIN PRODUCTREQUEST C ON B.CDPRODUCT = C.CDPRODUCT;

-- EXERCICIO D
SELECT 
	A.NMCUSTOMER,
	D.NMPRODUCT,
	SUM(B.VLTOTAL) AS VLREQUESTS
FROM CUSTOMER A
INNER JOIN REQUEST B ON A.CDCUSTOMER = B.CDCUSTOMER
INNER JOIN PRODUCTREQUEST C ON B.CDREQUEST = B.CDREQUEST
INNER JOIN PRODUCT D ON C.CDPRODUCT = C.CDPRODUCT
GROUP BY A.NMCUSTOMER, D.NMPRODUCT

UNION ALL

SELECT 
	A.NMCUSTOMER, 'TOTALCUSTOMER',
	SUM(B.VLTOTAL) AS VLREQUESTS
FROM CUSTOMER A
INNER JOIN REQUEST B ON A.CDCUSTOMER = B.CDCUSTOMER
INNER JOIN PRODUCTREQUEST C ON B.CDREQUEST = B.CDREQUEST
INNER JOIN PRODUCT D ON C.CDPRODUCT = C.CDPRODUCT
GROUP BY A.NMCUSTOMER

UNION ALL

SELECT 
	'TOTAL', '',
	SUM(B.VLTOTAL) AS TOTAL
FROM CUSTOMER A
INNER JOIN REQUEST B ON A.CDCUSTOMER = B.CDCUSTOMER
INNER JOIN PRODUCTREQUEST C ON B.CDREQUEST = B.CDREQUEST
INNER JOIN PRODUCT D ON C.CDPRODUCT = C.CDPRODUCT;

-- EXERCICIO E
SELECT NMCUSTOMER, IDFONE
FROM CUSTOMER WHERE CDCUSTOMER NOT IN(
	SELECT CDCUSTOMER FROM REQUEST);

-- EXERCICIO F
SELECT 
	A.NMSUPPLIER, A.IDFONE
FROM SUPPLIER A
INNER JOIN PRODUCT B ON A.CDSUPPLIER = B.CDSUPPLIER
WHERE B.NMPRODUCT like '%leite em po%' OR B.NMPRODUCT = '%agua mineral%'; -- Não tinha esse produtos na base

-- EXERCICIO G
SELECT 
	RESULT.NMPRODUCT, RESULT.NMSUPPLIER
FROM (SELECT 
	A.NMPRODUCT,
	B.NMSUPPLIER,
	COUNT(C.CDPRODUCT) AS TOTALSELLS
FROM PRODUCT A 
INNER JOIN SUPPLIER B ON A.CDSUPPLIER = B.CDSUPPLIER
INNER JOIN PRODUCTREQUEST C ON A.CDPRODUCT = C.CDPRODUCT
GROUP BY A.NMPRODUCT, B.NMSUPPLIER) AS RESULT
WHERE RESULT.TOTALSELLS > 3;
