-- EXERCICIO 1 - A
DELETE FROM CUSTOMER 
WHERE CDCUSTOMER NOT IN(
	SELECT CDCUSTOMER FROM REQUEST
);

-- EXERCICIO 1 - B 
DELETE FROM SUPPLIER
WHERE CDSUPPLIER NOT IN(
	SELECT CDSUPPLIER FROM PRODUCT
);

-- EXERCICIO 1 - C
BEGIN TRAN -- ATUALIZA O VALOR UNITÁRIO PELO VALOR DA TABELA DE PRODUTOS
UPDATE PRODUCTREQUEST
SET VLUNITARY = B.VLPRICE
FROM PRODUCTREQUEST A
INNER JOIN PRODUCT B ON A.CDPRODUCT = B.CDPRODUCT
WHERE A.VLUNITARY != B.VLPRICE;
ROLLBACK TRAN

BEGIN TRAN -- Atualiza o valor total da request com a soma dos valores dos produtos
UPDATE REQUEST
SET VLTOTAL = RESULT.TOTAL
FROM (
	SELECT
		CDREQUEST,
		SUM(VLUNITARY * QTAMOUNT) AS TOTAL
	FROM PRODUCTREQUEST
	GROUP BY CDREQUEST
) AS RESULT
WHERE REQUEST.CDREQUEST = RESULT.CDREQUEST
ROLLBACK TRAN

-- EXERCICIO 1 - D
ALTER TABLE SUPPLIER
ADD DSSTATUS VARCHAR(10) NULL;

-- EXERCICIO 1 - E
UPDATE SUPPLIER 
SET DSSTATUS = 'INATIVO'
WHERE CDSUPPLIER NOT IN (
	SELECT CDSUPPLIER FROM PRODUCT
);

-- EXERCICIO 1 - F
UPDATE CUSTOMER 
SET NMADRESS = 'DESCONHECIDO'
WHERE NMADRESS IS NULL;

-- EXERCICIO 1 - G
BEGIN TRAN
GO
DELETE FROM PRODUCTREQUEST
INSERT INTO PRODUCTREQUEST (A.CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)
SELECT A.CDREQUEST, B.CDPRODUCT, 10, B.VLPRICE FROM REQUEST A, PRODUCT B
GO
ROLLBACK TRAN
COMMIT TRAN

-- EXERCICIO 2 - A
SELECT 
	A.NMCUSTOMER,
	D.NMPRODUCT,
	COUNT(D.NMPRODUCT) AS TIMESBOUGHT,
	SUM(B.VLTOTAL) AS TOTALPAID
FROM CUSTOMER A
INNER JOIN REQUEST B ON A.CDCUSTOMER = B.CDCUSTOMER
INNER JOIN PRODUCTREQUEST C ON B.CDREQUEST = C.CDREQUEST
INNER JOIN PRODUCT D ON C.CDPRODUCT = D.CDPRODUCT 
GROUP BY A.NMCUSTOMER, D.NMPRODUCT
ORDER BY A.NMCUSTOMER;

-- EXERCICIO 2 - B
SELECT 
	NMCUSTOMER,
	COUNT(B.CDCUSTOMER) AS TOTALBOUGHTS,
	SUM(B.VLTOTAL)
FROM CUSTOMER A
INNER JOIN REQUEST B ON A.CDCUSTOMER = B.CDCUSTOMER
INNER JOIN PRODUCTREQUEST C ON B.CDREQUEST = C.CDREQUEST
INNER JOIN PRODUCT D ON C.CDPRODUCT = D.CDPRODUCT
WHERE YEAR(B.DTREQUEST) = 2003
GROUP BY NMCUSTOMER;

-- EXERCICIO 2 - C
SELECT
	A.NMSUPPLIER, A.IDFONE,
	B.NMPRODUCT
FROM SUPPLIER A 
INNER JOIN PRODUCT B ON A.CDSUPPLIER = B.CDSUPPLIER
WHERE A.CDSUPPLIER IN (
	SELECT CDSUPPLIER FROM PRODUCT B
) 
UNION ALL
SELECT
	NMSUPPLIER, IDFONE,
	NULL
FROM SUPPLIER 
WHERE CDSUPPLIER NOT IN (
	SELECT CDSUPPLIER FROM PRODUCT
);

-- EXERCICIO 2 - D
SELECT
	A.NMCUSTOMER, 
	B.DTREQUEST, B.VLTOTAL
FROM CUSTOMER A 
INNER JOIN REQUEST B ON A.CDCUSTOMER = B.CDCUSTOMER
WHERE A.CDCUSTOMER IN (
	SELECT CDSUPPLIER FROM PRODUCT B
) 
UNION ALL
SELECT
	NMCUSTOMER, 
	NULL, NULL
FROM CUSTOMER
WHERE CDCUSTOMER NOT IN (
	SELECT CDSUPPLIER FROM PRODUCT
);